In [ ]:
!pip3 install torch torchvision

In [ ]:
import torch
import torch.nn as nn

# Input Matrix

Syntax used: torch.tensor

torch.tensor is a multi-dimensional matrix containing elements of a single datatype.

In [ ]:
# Perceptron - algorithm that classifies into binary outcomes, either 0 or 1. 
#AND 
# Creating input tensor
input_tensor = torch.tensor([(0,0,1), (0,1,1), (1,0,1), (1,1,1)], dtype = torch.double)
print(input_tensor)

#The 3rd column would be the bias.

tensor([[0., 0., 1.],
        [0., 1., 1.],
        [1., 0., 1.],
        [1., 1., 1.]], dtype=torch.float64)


# AND

In [ ]:
# Creating the matric with the weights 

and_weights = torch.tensor([(10, 10, -20)], dtype = torch.double)
print(and_weights)

tensor([[ 10.,  10., -20.]], dtype=torch.float64)


In [ ]:
# Check the size of the matrices
print("input_tensor = ", input_tensor.shape)
print("and_weights = ", and_weights.shape)

input_tensor =  torch.Size([4, 3])
and_weights =  torch.Size([1, 3])


In [ ]:
# Carry out Matrix Multiplication => and_weights * input_tensor
and_logic = and_weights.mm(input_tensor.t()) 
print(and_logic)

tensor([[-20., -10., -10.,   0.]], dtype=torch.float64)


In [ ]:
# ___t.() transposes the matrix, from 4x3 to 3x4, therefore matrix multiplication is 1x3 * 3x4 = 1x4
input_tensor.t()

tensor([[0., 0., 1., 1.],
        [0., 1., 0., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)

In [ ]:
# Replacing the values with 0 and 1
and_output = [[1 if i>= 0 else 0 for i in x ]for x in and_logic]
print(and_output)

[[0, 0, 0, 1]]


# OR

In [ ]:
# Using the same input_tensor
# Creating the OR_weights

or_weights = torch.tensor([(20, 20, -10)], dtype = torch.double) #NOTE: the 3rd element is the BIAS
print(or_weights)
print("or_weights = ", or_weights.shape)

tensor([[ 20.,  20., -10.]], dtype=torch.float64)
or_weights =  torch.Size([1, 3])


In [ ]:
# Matrix Multiplication
or_logic = or_weights.mm(input_tensor.t())
print(or_logic)

tensor([[-10.,  10.,  10.,  30.]], dtype=torch.float64)


In [ ]:
or_output = [[1 if i>= 0 else 0 for i in x] for x in or_logic]
print(or_output)

[[0, 1, 1, 1]]


# NOT

In [ ]:
not_weights = torch.tensor([(10, -20, 1)], dtype = torch.double)
not_logic = not_weights.mm(input_tensor.t())
not_output = [[1 if i>= 0 else 0 for i in x]for x in not_logic]
print(not_output)

[[1, 0, 1, 0]]


# XOR

In [ ]:
# XOR
# 0 0 | 0
# 0 1 | 1
# 1 0 | 1
# 1 1 | 0

We are unable to implement the XOR Logic using just a Perceptron as the classes of the XOR Logic cannot be linearly separable, which means we cannot separate (0,0), (1,0), (0,1), (1,1) using just a linear line. Hence, we would need a neural network with mulitple layers.